/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author akshitsaxena
 */
public class MainFrame extends javax.swing.JFrame {

    private Person person;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CreatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        fnm = new javax.swing.JTextField();
        lnm = new javax.swing.JTextField();
        cnm = new javax.swing.JTextField();
        oph = new javax.swing.JTextField();
        oem = new javax.swing.JTextField();
        pph = new javax.swing.JTextField();
        pem = new javax.swing.JTextField();
        lst = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lap = new javax.swing.JTextField();
        lcit = new javax.swing.JTextField();
        lzi = new javax.swing.JTextField();
        pst = new javax.swing.JTextField();
        pap = new javax.swing.JTextField();
        pcit = new javax.swing.JTextField();
        pzi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ViewPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        viewnuid = new javax.swing.JLabel();
        viewfname = new javax.swing.JLabel();
        viewlname = new javax.swing.JLabel();
        viewcname = new javax.swing.JLabel();
        viewophone = new javax.swing.JLabel();
        viewoemail = new javax.swing.JLabel();
        viewpphone = new javax.swing.JLabel();
        viewpemail = new javax.swing.JLabel();
        viewlstreet = new javax.swing.JLabel();
        viewlapt = new javax.swing.JLabel();
        viewlcity = new javax.swing.JLabel();
        viewlzip = new javax.swing.JLabel();
        viewpstreet = new javax.swing.JLabel();
        viewpapt = new javax.swing.JLabel();
        viewpcity = new javax.swing.JLabel();
        viewpzip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreatePanel.setBackground(new java.awt.Color(255, 204, 204));
        CreatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("HUSKY CARD FORM");
        CreatePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 19, -1, -1));

        jLabel2.setText("NUID");
        CreatePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 53, -1, -1));

        jLabel3.setText("First Name");
        CreatePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 79, -1, -1));

        jLabel4.setText("Last Name");
        CreatePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 108, -1, -1));

        jLabel5.setText("College Name");
        CreatePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 137, -1, -1));

        jLabel6.setText("Contact Information");
        CreatePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 163, -1, -1));

        jLabel7.setText("Official");
        CreatePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 186, -1, -1));

        jLabel8.setText("Phone number");
        CreatePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 215, -1, -1));

        jLabel9.setText("email ID");
        CreatePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 238, -1, -1));

        jLabel10.setText("Personal");
        CreatePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 267, -1, -1));

        jLabel11.setText("Phone number");
        CreatePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 293, -1, -1));

        jLabel12.setText("email ID");
        CreatePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 322, -1, -1));

        jLabel13.setText("Address");
        CreatePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 348, -1, -1));

        jLabel14.setText("Local Address");
        CreatePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 371, -1, -1));

        jLabel15.setText("Street Name");
        CreatePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 397, -1, -1));

        jLabel16.setText("Apt. No");
        CreatePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 426, -1, -1));

        jLabel17.setText("City/State");
        CreatePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 455, -1, -1));

        jLabel18.setText("Zip code");
        CreatePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 484, -1, -1));

        nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidActionPerformed(evt);
            }
        });
        CreatePanel.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 47, 127, -1));

        fnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnmActionPerformed(evt);
            }
        });
        CreatePanel.add(fnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 76, 127, -1));

        lnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnmActionPerformed(evt);
            }
        });
        CreatePanel.add(lnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 105, 127, -1));
        CreatePanel.add(cnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 134, 127, -1));
        CreatePanel.add(oph, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 209, 127, -1));
        CreatePanel.add(oem, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 238, 127, -1));
        CreatePanel.add(pph, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 290, 127, -1));
        CreatePanel.add(pem, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 319, 127, -1));
        CreatePanel.add(lst, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 394, 127, -1));

        jLabel19.setText("Permanent Address");
        CreatePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 510, -1, -1));

        jLabel20.setText("Street Name");
        CreatePanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 536, -1, -1));

        jLabel21.setText("Apt. No");
        CreatePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 565, -1, -1));

        jLabel22.setText("City/State");
        CreatePanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 594, -1, -1));

        jLabel23.setText("Zip code");
        CreatePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 623, -1, -1));
        CreatePanel.add(lap, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 423, 127, -1));
        CreatePanel.add(lcit, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 452, 127, -1));
        CreatePanel.add(lzi, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 481, 127, -1));
        CreatePanel.add(pst, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 533, 127, -1));
        CreatePanel.add(pap, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 562, 127, -1));

        pcit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcitActionPerformed(evt);
            }
        });
        CreatePanel.add(pcit, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 591, 127, -1));
        CreatePanel.add(pzi, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 620, 127, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CreatePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 649, -1, -1));

        jSplitPane1.setLeftComponent(CreatePanel);

        ViewPanel.setBackground(new java.awt.Color(204, 204, 255));
        ViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("HUSKY CARD DETAILS");
        ViewPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 22, -1, -1));

        viewnuid.setText("nuid");
        ViewPanel.add(viewnuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 57, -1, -1));

        viewfname.setText("First Name");
        ViewPanel.add(viewfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 86, -1, -1));

        viewlname.setText("Last Name");
        ViewPanel.add(viewlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 115, -1, -1));

        viewcname.setText("College Name");
        ViewPanel.add(viewcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 144, -1, -1));

        viewophone.setText("Official Phone");
        ViewPanel.add(viewophone, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 212, -1, -1));

        viewoemail.setText("Official email");
        ViewPanel.add(viewoemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 241, -1, -1));

        viewpphone.setText("Personal Phone");
        ViewPanel.add(viewpphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 291, -1, -1));

        viewpemail.setText("Personal email");
        ViewPanel.add(viewpemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 320, -1, -1));

        viewlstreet.setText("Local Street");
        ViewPanel.add(viewlstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 395, -1, -1));

        viewlapt.setText("Local Apt");
        ViewPanel.add(viewlapt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 424, -1, -1));

        viewlcity.setText("Local City");
        ViewPanel.add(viewlcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 453, -1, -1));

        viewlzip.setText("Local zip");
        ViewPanel.add(viewlzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 482, -1, -1));

        viewpstreet.setText("Permanent Street");
        ViewPanel.add(viewpstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 538, -1, -1));

        viewpapt.setText("Permanent Apt");
        ViewPanel.add(viewpapt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 561, -1, -1));

        viewpcity.setText("Permanent City");
        ViewPanel.add(viewpcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 590, -1, -1));

        viewpzip.setText("Permanent zip");
        ViewPanel.add(viewpzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 619, -1, -1));

        jSplitPane1.setRightComponent(ViewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nuid = nid.getText();
        String fname = fnm.getText();
        String lname = lnm.getText();
        String cname = cnm.getText();
        long ophone = Long.valueOf(oph.getText());
        String oemail = oem.getText();
        long pphone = Long.valueOf(pph.getText());
        String pemail = pem.getText();
        String lstreet = lst.getText();
        long lapt = Long.valueOf(lap.getText());
        String lcity = lcit.getText();
        long lzip = Long.valueOf(lzi.getText());
        String pstreet = pst.getText();
        long papt = Long.valueOf(pap.getText());
        String pcity = pcit.getText();
        long pzip = Long.valueOf(pzi.getText());
        
        this.person.setNuid(nuid);
        this.person.setFname(fname);
        this.person.setLname(lname);
        this.person.setCname(cname);
        
        Address address = this.person.getAddress();
        address.setApt(lapt);
        address.setStreet(lstreet);
        address.setCity(lcity);
        address.setZip(lzip);
        
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setApt(papt);
        permanentAddress.setStreet(pstreet);
        permanentAddress.setCity(pcity);
        permanentAddress.setZip(pzip);
        
        Contact officialContact = this.person.getOfficialContact();
        officialContact.setPhoneNumber(ophone);
        officialContact.setEmailId(oemail);
        
        Contact personalContact = this.person.getPersonalContact();
        personalContact.setPhoneNumber(pphone);
        personalContact.setEmailId(pemail);
        display();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void display(){
        
        viewnuid.setText(this.person.getNuid());
        viewfname.setText(this.person.getFname());
        viewlname.setText(this.person.getLname());
        viewcname.setText(this.person.getCname());
        
        viewophone.setText(String.valueOf(this.person.getOfficialContact().getPhoneNumber()));
        viewoemail.setText(this.person.getOfficialContact().getEmailId());
        viewpphone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        viewpemail.setText(this.person.getPersonalContact().getEmailId());
        
        viewlapt.setText(String.valueOf(this.person.getAddress().getApt()));
        viewlstreet.setText(this.person.getAddress().getStreet());
        viewlcity.setText(this.person.getAddress().getCity());
        viewlzip.setText(String.valueOf(this.person.getAddress().getZip()));
        
        viewpapt.setText(String.valueOf(this.person.getPermanentAddress().getApt()));
        viewpstreet.setText(this.person.getPermanentAddress().getStreet());
        viewpcity.setText(this.person.getPermanentAddress().getCity());
        viewpzip.setText(String.valueOf(this.person.getPermanentAddress().getZip()));
        
    }
    private void fnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnmActionPerformed

    private void lnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnmActionPerformed

    private void pcitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatePanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JTextField cnm;
    private javax.swing.JTextField fnm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lap;
    private javax.swing.JTextField lcit;
    private javax.swing.JTextField lnm;
    private javax.swing.JTextField lst;
    private javax.swing.JTextField lzi;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField oem;
    private javax.swing.JTextField oph;
    private javax.swing.JTextField pap;
    private javax.swing.JTextField pcit;
    private javax.swing.JTextField pem;
    private javax.swing.JTextField pph;
    private javax.swing.JTextField pst;
    private javax.swing.JTextField pzi;
    private javax.swing.JLabel viewcname;
    private javax.swing.JLabel viewfname;
    private javax.swing.JLabel viewlapt;
    private javax.swing.JLabel viewlcity;
    private javax.swing.JLabel viewlname;
    private javax.swing.JLabel viewlstreet;
    private javax.swing.JLabel viewlzip;
    private javax.swing.JLabel viewnuid;
    private javax.swing.JLabel viewoemail;
    private javax.swing.JLabel viewophone;
    private javax.swing.JLabel viewpapt;
    private javax.swing.JLabel viewpcity;
    private javax.swing.JLabel viewpemail;
    private javax.swing.JLabel viewpphone;
    private javax.swing.JLabel viewpstreet;
    private javax.swing.JLabel viewpzip;
    // End of variables declaration//GEN-END:variables
}
